fix: filtering events requires obtaining the arena facet interface explicitly

diff --git a/tusk.yml b/tusk.yml
--- a/tusk.yml
+++ b/tusk.yml
@@ -4,182 +4,103 @@ options:
   launchdir:
     default:
       command: echo $PWD
+
+  walletsdir:
+    default: .local/dev/wallets
   openai-api-key:
     default:
       command: echo $ARENASTATE_OPENAI_API_KEY
 
 tasks:
-  showcfg:
+
+  fileorvalue:
+    usage: "echo the value, if value is a file read it from that."
+    args:
+      keyorfile:
+    run:
+      - command:
+          exec: |
+            set -e
+            if [ -f "${keyorfile}" ]; then
+              printf "%s" "$(<${keyorfile})"
+            else
+              echo -n "${keyorfile}"
+            fi
+
+  named-wallet:
+    usage: "echo the named private key, don't use with production keys"
     args:
       name:
+    options:
+      address:
+        type: bool
+        short: "a"
     run:
       - command:
           exec: |
             set -e
-            DIR=$(cd ${launchdir} && pwd)
-            cat $DIR/${name}.cfg.json
+            WALLETS_DIR=$(cd ${launchdir} && pwd)/${walletsdir}
+            SUFFIX=.key
+            ${address} && SUFFIX=.addr
+            [ ! -f ${WALLETS_DIR}/${name}${SUFFIX} ] && echo "${name}${SUFFIX} not found" && exit 1
+            printf "%s" "$(<${WALLETS_DIR}/${name}${SUFFIX})"
 
-  oai-list:
-    run:
-      - command:
-          exec: |
-            set -e
-            curl https://api.openai.com/v1/models \
-              -H "Authorization: Bearer ${openai-api-key}"
 
-  oai-model:
-    args:
-      model:
+  gen-hh-wallets:
+    usage: "usage save the well known hard hat keys as wallet files"
+    options:
+      dir:
+        default: .local/dev/wallets
     run:
       - command:
           exec: |
             set -e
-            curl https://api.openai.com/v1/models/${model} \
-              -H "Authorization: Bearer ${openai-api-key}"
-  oai-scene-text:
-    run:
-      - command:
-          exec: |
-            set -e
-            # "prompt": "In the voice of an adventure game, provide a discription of the scene observed by a player who just entered a room through its south door. Note that the room is part of a dungeon and the player is nervous of traps. The room has for sides. There are two doors in the east side. There is one door in the south side.",
-            curl -X POST https://api.openai.com/v1/completions \
-              -H 'Content-Type: application/json' \
-              -H 'Authorization: Bearer ${openai-api-key}' \
-              -d '{
-                "model": "text-davinci-003",
-                "prompt": "In the voice of an adventure game, provide a discription of the scene observed by a player who just entered a room through its south door. Note that the room is part of a dungeon and the player is nervous of traps. The room has for sides. There are two doors in the east side. There is one door in the south side.",
-                "max_tokens": 1024
-              }' | jq -r
-  oai-scene:
-    run:
-      - command:
-          exec: |
-            set -e
-            DIR=.local/dev/wallets
-            WALLET=$(cat $DIR/robin.addr)
-            curl -X POST https://api.openai.com/v1/images/generations \
-              -H 'Content-Type: application/json' \
-              -H 'Authorization: Bearer ${openai-api-key}' \
-              -d '{
-                "prompt": "Your eyes scan the room nervously, looking for traps. You note the door you just stepped through in the south side, and two doors on the east side. The walls of the room are lined with ancient stone and the air is humid and stale - a stark reminder that you are underground in a dungeon. You take a deep breath in preparation for what the next room may hold",
-                
-                "n": 2,
-                "size": "512x512",
-                "response_format": "url"
-              }' | jq -r
+            WALLETS_DIR=$(cd ${launchdir} && pwd)/${dir}
+            mkdir -p $WALLETS_DIR
 
-  oai-game-icon:
-    run:
-      - command:
-          exec: |
-            set -e
-            DIR=.local/dev/wallets
-            WALLET=$(cat $DIR/robin.addr)
-            curl -X POST https://api.openai.com/v1/images/generations \
-              -H 'Content-Type: application/json' \
-              -H 'Authorization: Bearer ${openai-api-key}' \
-              -d '{
-                "prompt": "A stylised icon representing a turn based random dungeon crawler game",
-                
-                "n": 2,
-                "size": "512x512",
-                "response_format": "b64_json"
-              }' | jq -r
+            keys=(
+              0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 \
+              0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d \
+              0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a \
+              0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6 \
+              0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a \
+              0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba \
+              0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e \
+              0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356 \
+              0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97 \
+              0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6 \
+              0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897 \
+              0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82 \
+              0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1 \
+              0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd \
+              0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa \
+              0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61 \
+              0xea6c44ac03bff858b476bba40716402b03e41b8e97e276d1baec7c37d42484a0 \
+              0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd \
+              0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0 \
+              0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e)
+
+            for i in ${!keys[@]}; do
+              echo -n ${keys[$i]} > $WALLETS_DIR/hardhat-$i.key
+              cast wallet address ${keys[$i]} | tr -d '\n' > $WALLETS_DIR/hardhat-$i.addr
+              cat $WALLETS_DIR/hardhat-$i.key
+              echo
+              cat $WALLETS_DIR/hardhat-$i.addr
+              echo
+            done
 
   new-wallet:
     args:
       name:
+    options:
+      dir:
+        default: .local/dev/wallets
     run:
       - command:
           exec: |
             set -e
-            DIR=.local/dev/wallets
+            DIR=${dir}
             mkdir -p $DIR
             cast wallet new > $DIR/${name}.txt
             cat $DIR/${name}.txt | egrep "^Address: " | cut -d ' ' -f2 > $DIR/${name}.addr
             cat $DIR/${name}.txt | egrep "^Private Key: " | cut -d ' ' -f3 > $DIR/${name}.key
-
-  wallet:
-    args:
-      name:
-    run:
-      - command:
-          exec: |
-            DIR=.local/dev/wallets
-            cat $DIR/${name}.addr
-  key:
-    args:
-      name:
-    run:
-      - command:
-          exec: |
-            DIR=.local/dev/wallets
-            cat $DIR/${name}.key
-  keyfile:
-    args:
-      name:
-    run:
-      - echo $(pwd)/.local/dev/wallets/${name}.key
-
-  cfg:
-    options:
-      force:
-        type: bool
-        default: false
-        short: "f"
-      verbose:
-        default: true
-      chain-url:
-        default: https://chains.hoy.polysensus.io/chains/caimst-209301/node/ethnode0/WWdEOHJUNVFDRXpPZ0VDb1IxTVpYOmFyZ29uMmlkIDMgNjRNQiAzMi5Kdkt6cEU5U09HNW02a3RBXzViYk8yRFZNeUw3cXBEdm5vQjhlOEtQMk5rPS5pR2JMMXpDRzBxbVRKdnRUN2RkLURxWlhSbDkxTWlYQm1RNDlKVzhjOF9jPQ==
-      providers:
-        short: "p"
-      deploykey:
-        short: "d"
-      key:
-        short: "k"
-      deployacc:
-      abi:
-      map:
-      key1:
-      key2:
-      key3:
-    args:
-      name:
-    run:
-      - command:
-          exec: |
-            DIR=$(cd ${launchdir} && pwd)
-            mkdir -p $DIR
-            CFG=$DIR/${name}.cfg.json
-            ${force} && rm -f $CFG
-            [ -f ${CFG} ] && echo "$CFG exists, -f to force" && exit 1
-
-            # TODO: use https://github.com/jpmens/jo/blob/master/jo.md
-
-            echo "{" >> $CFG
-            [ -n "${verbose}" ] && \
-            echo '  "verbose": "${verbose}",' >> $CFG
-            [ -n "${chain-url}" ] && \
-            echo '  "chain-url": "${chain-url}",' >> $CFG
-            [ -n "${providers}" ] && \
-            echo '  "providers": "${providers}",' >> $CFG
-            [ -n "${deploykey}" ] && \
-            echo '  "deploykey": "${deploykey}",' >> $CFG
-            [ -n "${deployacc}" ] && \
-            echo '  "deployacc": "${deployacc}",' >> $CFG
-            [ -n "${abi}" ] && \
-            echo '  "abi": "${abi}",' >> $CFG
-            [ -n "${map}" ] && \
-            echo '  "map": "${map}",' >> $CFG
-            [ -n "${key}" ] && \
-            echo '  "key": "${key}",' >> $CFG
-            [ -n "${key1}" ] && \
-            echo '  "key1": "${key1}",' >> $CFG
-            [ -n "${key2}" ] && \
-            echo '  "key2": "${key2}",' >> $CFG
-            [ -n "${key3}" ] && \
-            echo '  "key3": "${key3}",' >> $CFG
-
-            # easiest way to deal with traling ',' is to put this one last
-            echo "  \"launchdir\": \"$DIR\"" >> $CFG
-            echo '}' >> $CFG
